INSERT INTO CLASSROOM VALUES(UUID(), '1A');

INSERT INTO CLASSROOM VALUES(UUID(), '1B');

INSERT INTO CLASSROOM VALUES(UUID(), '1C');

INSERT INTO STUDENT VALUES(UUID(), 'John', 100, NULL);

INSERT INTO STUDENT VALUES(UUID(), 'John2', 75, NULL);

INSERT INTO STUDENT VALUES(UUID(), 'John3', 50, NULL);