### Variables
@port = 8080
@baseUrl = http://localhost:{{port}}

### Root 
GET {{baseUrl}} HTTP/1.1

### Root - Localized
GET {{baseUrl}} HTTP/1.1
Accept-Language: in-ID

### Get Classroom
GET {{baseUrl}}/classroom/1A HTTP/1.1

### Save Classroom
POST {{baseUrl}}/classroom/save HTTP/1.1
Content-Type: application/json

{
    "roomName": "2A"
}

### Save and redirect Classroom
POST {{baseUrl}}/classroom/saveandredirect HTTP/1.1
Content-Type: application/json

{
    "roomName": "2B"
}

### Get Student
GET {{baseUrl}}/student/John HTTP/1.1

### Get Students by Class
GET {{baseUrl}}/student/class/1A HTTP/1.1

### Save Student
POST {{baseUrl}}/student/save HTTP/1.1
Content-Type: application/json

{
    "name": "Jane1",
    "score": 65,
    "classroomName": "1A"
}
###
POST {{baseUrl}}/student/save HTTP/1.1
Content-Type: application/json

{
    "name": "Jane2",
    "score": 66,
    "classroomName": "1A"
}
###
POST {{baseUrl}}/student/save HTTP/1.1
Content-Type: application/json

{
    "name": "Jane3",
    "score": 67,
    "classroomName": "1A"
}