### Root 
GET http://localhost:8080/ HTTP/1.1

### Get Classroom
GET http://localhost:8080/classroom/1A HTTP/1.1

### Save Classroom
POST http://localhost:8080/classroom/save HTTP/1.1
Content-Type: application/json

{
    "roomName": "2A"
}

### Save and redirect
POST http://localhost:8080/classroom/saveandredirect HTTP/1.1
Content-Type: application/json

{
    "roomName": "2B"
}
